syntax = "proto3";

package calculator;

option go_package = "/proto/gen;genpb";

service Calculator {
    rpc Add (AddRequest) returns (AddResponse);
    rpc Subtract (SubtractRequest) returns (SubtractResponse);
    rpc Multiply (MultiplyRequest) returns (MultiplyResponse);
    rpc Divide (DivideRequest) returns (DivideResponse);
}

message AddRequest {
    int32 A = 1;
    int32 B = 2;
}

message AddResponse {
  int32 sum = 1;
}

message SubtractRequest {
    int32 A = 1;
    int32 B = 2;
}

message SubtractResponse {
    int32 difference = 1;
}

message MultiplyRequest {
    int32 A = 1;
    int32 B = 2;
}

message MultiplyResponse {
    int32 product = 1;
}

message DivideRequest {
    int32 A = 1;
    int32 B = 2;
}

message DivideResponse {
    float quotient = 1;
}
